trigger:
- Main
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'  
stages:
- stage: BuildStage
  displayName: 'Stage - Build'
  jobs:
  - job: Checkout
    steps:
    - checkout: self
      displayName: 'Checkout code from main branch'
  - job: Install_Net_Core_SDK
    steps:
    - task: UseDotNet@2
      inputs:
        version: '8.0.x'
        dependsOn: Checkout
        displayName: 'Install .NET Core SDK'
        
  - job: Restore_NuGet_Packages
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        dependsOn: Install_Net_Core_SDK
        projects: '**/*.csproj'
      displayName: 'Restore_NuGet_Packages'

  - job: Build_Project
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        dependsOn: Restore_NuGet_Packages
        projects: '**/*.csproj'
        displayName: 'Build_Project'

  - job: Publish
    steps:
    - task: DotNetCoreCLI@2
      inputs: 
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterpublish: True

  - job: PublishToArtifact
    steps:
    - task: PublishPipelineArtifact@1
      inputs: 
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'FirstWebsite'
   